version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV_FILE=.env
    volumes:
      - ./backend/:/app
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENV_FILE=.env
    volumes:
      - ./frontend:/app
      - web-node-modules-data:/app/node_modules 
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - "9001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  web-node-modules-data: